-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 21:12:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdSupreme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdSupreme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdSupreme` DEFAULT CHARACTER SET utf8 ;
USE `bdSupreme` ;

-- -----------------------------------------------------
-- Table `bdSupreme`.`GERENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`GERENTE` (
  `ger_codigo` INT NOT NULL AUTO_INCREMENT,
  `ger_nome` VARCHAR(100) NOT NULL,
  `ger_cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ger_codigo`),
  UNIQUE INDEX `ger_cpf_UNIQUE` (`ger_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`ITEM` (
  `itm_codigo` INT NOT NULL AUTO_INCREMENT,
  `itm_nome` VARCHAR(100) NOT NULL,
  `itm_descricao` VARCHAR(500) NOT NULL,
  `itm_valor` DOUBLE NOT NULL,
  PRIMARY KEY (`itm_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`GARCOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`GARCOM` (
  `gar_codigo` INT NOT NULL AUTO_INCREMENT,
  `gar_nome` VARCHAR(100) NOT NULL,
  `gar_cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`gar_codigo`),
  UNIQUE INDEX `gar_cpf_UNIQUE` (`gar_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`PEDIDO` (
  `ped_codigo` INT NOT NULL AUTO_INCREMENT,
  `ped_itens` INT NOT NULL,
  `ped_valor` DOUBLE NOT NULL,
  `ped_mesa` INT NOT NULL,
  `ped_status` VARCHAR(100) NOT NULL,
  `GARCOM_gar_codigo` INT NOT NULL,
  PRIMARY KEY (`ped_codigo`),
  INDEX `cod_item_idx` (`ped_itens` ASC),
  INDEX `cod_mesa_idx` (`ped_mesa` ASC),
  INDEX `fk_PEDIDO_GARCOM1_idx` (`GARCOM_gar_codigo` ASC),
  CONSTRAINT `PEDIDO_itm_codigo`
    FOREIGN KEY (`ped_itens`)
    REFERENCES `bdSupreme`.`ITEM` (`itm_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDIDO_mesa_codigo`
    FOREIGN KEY (`ped_mesa`)
    REFERENCES `bdSupreme`.`MESA` (`mesa_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PEDIDO_gar_codigo`
    FOREIGN KEY (`GARCOM_gar_codigo`)
    REFERENCES `bdSupreme`.`GARCOM` (`gar_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`CONTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`CONTA` (
  `conta_codigo` INT NOT NULL AUTO_INCREMENT,
  `conta_pedidos` INT NOT NULL,
  `conta_valor` DOUBLE NOT NULL,
  PRIMARY KEY (`conta_codigo`),
  INDEX `cod_pedido_idx` (`conta_pedidos` ASC),
  CONSTRAINT `CONTA_ped_codigo`
    FOREIGN KEY (`conta_pedidos`)
    REFERENCES `bdSupreme`.`PEDIDO` (`ped_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`MESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`MESA` (
  `mesa_codigo` INT NOT NULL AUTO_INCREMENT,
  `mesa_numero` INT NOT NULL,
  `mesa_pedidos` INT NOT NULL,
  `mesa_conta` INT NOT NULL,
  INDEX `cod_pedido_idx` (`mesa_pedidos` ASC),
  INDEX `cod_conta_idx` (`mesa_conta` ASC),
  PRIMARY KEY (`mesa_codigo`),
  CONSTRAINT `MESA_codigo_pedido`
    FOREIGN KEY (`mesa_pedidos`)
    REFERENCES `bdSupreme`.`PEDIDO` (`ped_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MESA_codigo_conta`
    FOREIGN KEY (`mesa_conta`)
    REFERENCES `bdSupreme`.`CONTA` (`conta_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`CLIENTE` (
  `cli_codigo` INT NOT NULL AUTO_INCREMENT,
  `cli_nome` VARCHAR(100) NOT NULL,
  `cli_cpf` VARCHAR(14) NOT NULL,
  `cod_mesa` INT NOT NULL,
  PRIMARY KEY (`cli_codigo`),
  INDEX `fk_CLIENTE_MESA1_idx` (`cod_mesa` ASC),
  UNIQUE INDEX `cli_cpf_UNIQUE` (`cli_cpf` ASC),
  CONSTRAINT `CLIENTE_mesa_codigo`
    FOREIGN KEY (`cod_mesa`)
    REFERENCES `bdSupreme`.`MESA` (`mesa_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`CAIXA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`CAIXA` (
  `cxa_codigo` INT NOT NULL AUTO_INCREMENT,
  `cxa_conta` INT NOT NULL,
  PRIMARY KEY (`cxa_codigo`),
  CONSTRAINT `CAIXA_conta_codigo`
    FOREIGN KEY (`cxa_conta`)
    REFERENCES `bdSupreme`.`CONTA` (`conta_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdSupreme`.`COZINHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdSupreme`.`COZINHA` (
  `coz_codigo` INT NOT NULL AUTO_INCREMENT,
  `coz_pedidos` INT NOT NULL,
  PRIMARY KEY (`coz_codigo`),
  INDEX `cod_pedido_idx` (`coz_pedidos` ASC),
  CONSTRAINT `COZINHA_ped_codigo`
    FOREIGN KEY (`coz_pedidos`)
    REFERENCES `bdSupreme`.`PEDIDO` (`ped_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
